redis:
  enabled: true

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

  hosts:
    - paths:
        - path: /
          pathType: Prefix
